/**
 * Generates supabase/seed.sql from the same layouts and demo data the app uses.
 * Run: node --experimental-strip-types scripts/generate-seed.ts
 */
import { writeFileSync } from 'node:fs';
import { LAYOUTS } from '../src/data/layouts.ts';
import { DEFAULT_PRICES, MOCK_REGISTRY, SEED_MOVIES, SEED_THEATRES, THEATRE_ROTATION } from '../src/data/seed.ts';

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (a: string[]) => `array[${a.map(q).join(', ')}]::text[]`;
const lines: string[] = [];
const out = (s: string) => lines.push(s);

out('-- Generated by scripts/generate-seed.ts — do not edit by hand.');
out('-- Kerketta Auditorium data (movie, history, schedule, seat chart) comes from the reference site.');
out('begin;');
out('');
out('-- Demo service registry (MOCK — not a real military database)');
for (const r of MOCK_REGISTRY) {
  out(`insert into service_registry_demo values (${q(r.serviceId)}, ${q(r.fullName)}, ${q(r.rankTitle)}, '${r.rankCategory}', ${q(r.unit)}) on conflict do nothing;`);
}
out('');
out('-- Movies (upcoming demo titles get release dates relative to today)');
SEED_MOVIES.forEach((m, i) => {
  const release = m.status === 'upcoming' ? `current_date + ${20 + i * 7}` : `'${m.releaseDate}'`;
  out(
    `insert into movies (slug, title, tagline, description, genres, language, duration_min, certification, release_date, director, cast_members, status, featured, palette) values (` +
      [q(m.slug), q(m.title), q(m.tagline), q(m.description), arr(m.genres), q(m.language), m.durationMin, q(m.certification), release, q(m.director), arr(m.cast), `'${m.status}'`, m.featured, arr(m.palette)].join(', ') +
      ') on conflict (slug) do nothing;',
  );
});
out('');
out('-- Theatres and their main screens');
for (const t of SEED_THEATRES) {
  out(
    `insert into theatres (slug, name, location, city, description, facilities, layout_key, weekly_schedule) values (` +
      [q(t.slug), q(t.name), q(t.location), q(t.city), q(t.description), arr(t.facilities), q(t.layoutKey), q(JSON.stringify(t.weeklySchedule)) + '::jsonb'].join(', ') +
      ') on conflict (slug) do nothing;',
  );
  out(`insert into screens (theatre_id, name, layout_key) select id, 'Main Hall', layout_key from theatres where slug = ${q(t.slug)} and not exists (select 1 from screens s where s.theatre_id = theatres.id);`);
}
out('');
out('-- Seats for every screen, generated from the layout definitions');
for (const t of SEED_THEATRES) {
  const layout = LAYOUTS[t.layoutKey];
  const values: string[] = [];
  for (const c of layout.categories)
    for (const r of c.rows)
      for (const it of r.items)
        if (it.kind === 'seat') {
          const s = it.seat;
          values.push(`(${q(s.id)}, ${q(s.row)}, ${s.number}, '${s.category}', ${q(s.type)}, ${q(s.blocked)})`);
        }
  out(`insert into seats (screen_id, code, row_label, seat_number, category, seat_type, blocked_reason)`);
  out(`select sc.id, v.code, v.row_label, v.seat_number, v.category::rank_category, v.seat_type, v.blocked_reason`);
  out(`from screens sc join theatres th on th.id = sc.theatre_id, (values`);
  out(values.map((v) => '  ' + v).join(',\n'));
  out(`) as v(code, row_label, seat_number, category, seat_type, blocked_reason)`);
  out(`where th.slug = ${q(t.slug)} on conflict do nothing;`);
}
out('');
out('-- Shows for the next 14 days from each theatre\'s weekly schedule');
for (const t of SEED_THEATRES) {
  const rotation = (THEATRE_ROTATION[t.id] ?? []).map((id) => SEED_MOVIES.find((m) => m.id === id)!.slug);
  out(`insert into shows (movie_id, theatre_id, screen_id, show_date, show_time, price_offrs, price_jcos, price_ors)`);
  out(`select m.id, th.id, sc.id, d::date, slot.value::time, ${DEFAULT_PRICES.OFFRS}, ${DEFAULT_PRICES.JCOS}, ${DEFAULT_PRICES.ORS}`);
  out(`from theatres th join screens sc on sc.theatre_id = th.id`);
  out(`cross join generate_series(current_date, current_date + 13, interval '1 day') d`);
  out(`cross join lateral jsonb_array_elements_text(th.weekly_schedule -> extract(dow from d)::int::text) with ordinality as slot(value, idx)`);
  out(`join movies m on m.slug = (${arr(rotation)})[1 + ((extract(doy from d)::int + slot.idx::int) % ${rotation.length})]`);
  out(`where th.slug = ${q(t.slug)} on conflict do nothing;`);
}
out('');
out('commit;');
out('');
out('-- After registering your admin account in the app, promote it:');
out("-- insert into admin_users (user_id) select id from profiles where email = 'you@example.com';");

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log(`seed.sql written (${lines.length} lines)`);
for (const l of Object.values(LAYOUTS)) console.log(l.key, 'capacity', l.capacity, l.categories.map((c) => `${c.key} ${c.total}/${c.bookable}`).join(', '));
